input {
  file {
    path => "/Users/ricky/Ricky's Desk/কার্যক্রম/Spark-Scala-Experiment/1672391800_00000887_0000.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json {
      target => "data"
    }
  }
}

output {
  kafka {
    bootstrap_servers => "localhost:9092"
    topic_id => "network-topic"
    codec => json   # IMPORTANT
  }

  stdout { codec => rubydebug }
}