input {
  file {
    path => "/data/1672391800_00000887_0000.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json {
      target => "data"
    }
  }
}

output {
  kafka {
    bootstrap_servers => "broker:9092"
    topic_id => "network-topic"
    codec => json
  }
  stdout { codec => rubydebug }
}